#!/bin/bash
git rev-parse HEAD
GIT_EDITOR="awk -i inplace '/pick/{c++; if (c>=2) { sub(\"pick\",\"fixup\")}}1'" git rebase -i --root
git reflog expire --expire=now --all
git repack -ad
git prune
git gc

n=0
until [ $n -ge 5 ]
do
  n=$[$n+1]
  git push -f && break
done
