#!/bin/bash

for i in "$@"; do ./.twsave.extractor.js "$i"; ./.twsave.extractor.js "$i/replies"; done | \
  grep -Eo 'status/[0-9]+' | \
  grep -Eo '[0-9]+' | \
  sort -u | \
  while read line ; do \
    torsocks wget -qO- 'https://tweetsave.com/api.php?mode=save&tweet='$line | jq '.redirect'
  done

exit 0
