#!/bin/bash

twdl () {
    python3 $(which youtube-dl) --cookies=$HOME/ck.txt --output='Twitter-%(uploader_id)s-%(id)s.%(ext)s' "$@"
}

wget -qO- https://twitter.com/$1{,/media} | \
  grep -Eo 'status/[0-9]+' | \
  grep -Eo '[0-9]+' | \
  sort -u | \
  while read line ; do \
    twdl "https://twitter.com/i/web/status/$line"
  done
